# примеры API-запросов

@baseUrl = http://localhost:8000/api/v1

# создание продукта
POST {{baseUrl}}/products/
Content-Type: application/json

{
  "title": "Помидор",
  "description": "Лучшие помидоры на рынке"
}

###

POST {{baseUrl}}/products/
Content-Type: application/json

{
  "title": "Морковка",
  "description": "Для зрения находка"
}

###

POST {{baseUrl}}/products/
Content-Type: application/json

{
  "title": "Арбуз",
  "description": "Этакий карапуз"
}

###

# получение продуктов
GET {{baseUrl}}/products/
Content-Type: application/json

###

# обновление продукта
PATCH {{baseUrl}}/products/3/
Content-Type: application/json

{
  "description": "Протух"
}

###

# удаление продукта
DELETE {{baseUrl}}/products/4/
Content-Type: application/json



###

# поиск продуктов по названию и описанию
GET {{baseUrl}}/products/?search=огур
Content-Type: application/json

###

# создание склада
POST {{baseUrl}}/stocks/
Content-Type: application/json

{
  "address": "2 мой адрес не дом и не улица, мой адрес сегодня такой: www.ленинград-спб.ru3",
  "positions": [
    {
      "product": 2,
      "quantity": 250,
      "price": 120.50
    },
    {
      "product": 3,
      "quantity": 100,
      "price": 180
    }
  ]
}

###

# удаление склада
DELETE {{baseUrl}}/stocks/14/
Content-Type: application/json
###

# обновляем записи на складе
PATCH {{baseUrl}}/stocks/16/
Content-Type: application/json

{
  "positions": [
    {
      "product": 2,
      "quantity": 1010,
      "price": 130.80
    },
    {
      "product": 3,
      "quantity": 243,
      "price": 145
    }
  ]
}

###

# поиск складов, где есть определенный продукт
GET {{baseUrl}}/stocks/?products=3
Content-Type: application/json
###

# поиск складов, где есть определенный продукт
GET {{baseUrl}}/stocks/
Content-Type: application/json
###


# поиск складов, где есть определенный продукт
GET {{baseUrl}}/stocks/?search=арб
Content-Type: application/json